/**
 * AI Estimation Service
 *
 * 매일 자정(KST) 서비스별 전일 DAU + 설명을 시스템 LLM에 보내
 * M/M 절감 효과를 추정하여 ai_estimations 테이블에 저장.
 */

import { prisma } from '../index.js';

const ESTIMATION_INTERVAL_MS = 60 * 60 * 1000; // 1시간마다 체크
const LLM_TIMEOUT_MS = 60_000; // 60초
const DELAY_BETWEEN_CALLS_MS = 2_000; // 서비스 간 2초 딜레이 (rate limit 방지)
const RETENTION_DAYS = 90;

let estimationInterval: ReturnType<typeof setInterval> | null = null;
let lastRunDate = ''; // YYYY-MM-DD 형식 — 하루에 한 번만 실행

// ── System Prompt ──
const SYSTEM_PROMPT = `You are an expert business analyst specializing in IT workforce productivity measurement.
Your task is to estimate the current M/M (Man-Month) cost savings generated by an AI-powered service based on its usage data and description.

Key definitions:
- 1 M/M = 1 person working full-time for 1 month (≈20 business days, 160 hours)
- 1 M/D = 1 person working 1 full day = 0.05 M/M

You must respond ONLY with valid JSON, no other text.`;

// ── LLM 호출 ──
async function callSystemLlm(
  model: { name: string; endpointUrl: string; apiKey: string | null; extraHeaders: unknown; extraBody: unknown },
  prompt: string,
): Promise<string> {
  let url = model.endpointUrl.trim();
  if (!url.endsWith('/chat/completions')) {
    if (url.endsWith('/')) url = url.slice(0, -1);
    // /v1으로 끝나면 /chat/completions만 추가, 아니면 그대로 /chat/completions 추가
    // (대부분의 엔드포인트 URL은 이미 /v1까지 포함하거나, /chat/completions를 포함)
    url = `${url}/chat/completions`;
  }

  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (model.apiKey) headers['Authorization'] = `Bearer ${model.apiKey}`;
  if (model.extraHeaders && typeof model.extraHeaders === 'object') {
    for (const [k, v] of Object.entries(model.extraHeaders as Record<string, string>)) {
      const lower = k.toLowerCase();
      if (lower !== 'content-type' && lower !== 'authorization') headers[k] = v;
    }
  }

  const body = {
    ...(model.extraBody && typeof model.extraBody === 'object' ? model.extraBody : {}),
    model: model.name,
    messages: [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: prompt },
    ],
    max_tokens: 1024,
    temperature: 0.3,
    stream: false,
  };

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), LLM_TIMEOUT_MS);

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers,
      body: JSON.stringify(body),
      signal: controller.signal,
    });
    clearTimeout(timeoutId);

    if (!response.ok) {
      const errText = await response.text().catch(() => '');
      throw new Error(`LLM ${response.status}: ${errText.substring(0, 300)}`);
    }

    const data = await response.json() as { choices?: Array<{ message?: { content?: string } }> };
    return data.choices?.[0]?.message?.content || '';
  } catch (err) {
    clearTimeout(timeoutId);
    throw err;
  }
}

// ── 프롬프트 빌더 ──
function buildPrompt(service: {
  displayName: string;
  type: string;
  description: string | null;
  standardMD: number | null;
  targetMM: number | null;
  savedMM: number | null;
  createdAt: Date;
}, dau: number, isEstimatedDau: boolean, totalCalls: number): string {
  const lines = [
    `Estimate the M/M savings for this AI service:`,
    ``,
    `Service: ${service.displayName}`,
    `Type: ${service.type} (${service.type === 'STANDARD' ? 'interactive user-facing' : 'automated batch processing'})`,
    `Description: ${service.description || 'No description'}`,
  ];

  if (service.type === 'BACKGROUND' && service.standardMD) {
    lines.push(`Standard workload per task: ${service.standardMD} M/D`);
  }

  lines.push(
    ``,
    `Yesterday's data:`,
    `- DAU: ${dau}${isEstimatedDau ? ' (estimated from API call volume)' : ''}`,
    `- Total API calls: ${totalCalls}`,
    ``,
    `Context:`,
    `- Running since: ${service.createdAt.toISOString().split('T')[0]}`,
    `- Owner's target M/M: ${service.targetMM ?? 'not set'}`,
    `- Manually recorded Saved M/M: ${service.savedMM ?? 'not set'}`,
  );

  if (service.type === 'BACKGROUND' && service.standardMD) {
    lines.push(`- For BACKGROUND: Saved M/M ≈ daily_tasks × ${service.standardMD} M/D ÷ 20`);
  }

  lines.push(
    ``,
    `Respond in JSON:`,
    `{"estimatedMM": <number 1 decimal>, "confidence": "HIGH"|"MEDIUM"|"LOW", "reasoning": "<2-3 sentences in Korean>"}`,
  );

  return lines.join('\n');
}

// ── JSON 파싱 (안전) ──
function parseEstimation(raw: string): { estimatedMM: number; confidence: string; reasoning: string } | null {
  try {
    // JSON 블록 추출 (```json ... ``` 감싸기 대응)
    const jsonMatch = raw.match(/\{[\s\S]*"estimatedMM"[\s\S]*\}/);
    if (!jsonMatch) return null;
    const parsed = JSON.parse(jsonMatch[0]);
    const mm = parseFloat(parsed.estimatedMM);
    if (isNaN(mm)) return null;
    return {
      estimatedMM: Math.round(mm * 10) / 10,
      confidence: ['HIGH', 'MEDIUM', 'LOW'].includes(parsed.confidence) ? parsed.confidence : 'MEDIUM',
      reasoning: String(parsed.reasoning || '').substring(0, 2000),
    };
  } catch {
    return null;
  }
}

// ── 전일 DAU + 호출 수 조회 ──
async function getYesterdayStats(yesterday: Date) {
  const dayStart = new Date(yesterday);
  dayStart.setHours(0, 0, 0, 0);
  const dayEnd = new Date(yesterday);
  dayEnd.setHours(23, 59, 59, 999);

  // STANDARD: 서비스별 실제 DAU + 호출 수
  const standardStats = await prisma.$queryRaw<
    Array<{ service_id: string; dau: bigint; calls: bigint }>
  >`
    SELECT ul.service_id::text as service_id,
           COUNT(DISTINCT ul.user_id) as dau,
           COUNT(*) as calls
    FROM usage_logs ul
    INNER JOIN users u ON ul.user_id = u.id
    WHERE ul.timestamp >= ${dayStart} AND ul.timestamp <= ${dayEnd}
      AND u.loginid != 'anonymous'
      AND ul.service_id IS NOT NULL
    GROUP BY ul.service_id
  `;

  // BACKGROUND: 호출 수만 (DAU는 추정 필요)
  const bgStats = await prisma.$queryRaw<
    Array<{ service_id: string; calls: bigint }>
  >`
    SELECT service_id::text as service_id, COUNT(*) as calls
    FROM usage_logs
    WHERE timestamp >= ${dayStart} AND timestamp <= ${dayEnd}
      AND service_id IS NOT NULL
    GROUP BY service_id
  `;

  // STANDARD 기준 1인당 하루 평균 호출 수 (추정 베이스라인)
  let totalStdCalls = 0;
  let totalStdDau = 0;
  for (const row of standardStats) {
    totalStdCalls += Number(row.calls);
    totalStdDau += Number(row.dau);
  }
  const callsPerPersonPerDay = totalStdDau > 0 ? totalStdCalls / totalStdDau : 0;

  const stdMap = new Map(standardStats.map(r => [r.service_id, { dau: Number(r.dau), calls: Number(r.calls) }]));
  const bgMap = new Map(bgStats.map(r => [r.service_id, Number(r.calls)]));

  return { stdMap, bgMap, callsPerPersonPerDay };
}

// ── 메인 실행 ──
export async function runAiEstimations(): Promise<{ processed: number; errors: number }> {
  // 1. 시스템 LLM 설정 확인
  const setting = await prisma.systemSetting.findUnique({ where: { key: 'SYSTEM_LLM_MODEL_ID' } });
  if (!setting?.value) {
    console.log('[AiEstimation] System LLM not configured — skipping');
    return { processed: 0, errors: 0 };
  }

  const model = await prisma.model.findUnique({
    where: { id: setting.value },
    select: { id: true, name: true, endpointUrl: true, apiKey: true, extraHeaders: true, extraBody: true, enabled: true, type: true },
  });
  if (!model || !model.enabled || model.type !== 'CHAT') {
    console.log('[AiEstimation] System LLM not found, disabled, or not CHAT type — skipping');
    return { processed: 0, errors: 0 };
  }

  // 2. 전일 날짜 (KST)
  const now = new Date();
  const kstNow = new Date(now.getTime() + 9 * 60 * 60 * 1000);
  const yesterday = new Date(kstNow);
  yesterday.setDate(yesterday.getDate() - 1);
  const yesterdayDate = new Date(Date.UTC(yesterday.getUTCFullYear(), yesterday.getUTCMonth(), yesterday.getUTCDate()));

  // 3. 배포된 서비스 목록
  const services = await prisma.service.findMany({
    where: { status: 'DEPLOYED' },
    select: {
      id: true, name: true, displayName: true, description: true,
      type: true, standardMD: true, targetMM: true, savedMM: true, createdAt: true,
    },
  });

  if (services.length === 0) {
    console.log('[AiEstimation] No deployed services — skipping');
    return { processed: 0, errors: 0 };
  }

  // 4. 전일 사용 통계
  const { stdMap, bgMap, callsPerPersonPerDay } = await getYesterdayStats(yesterdayDate);

  let processed = 0;
  let errors = 0;

  console.log(`[AiEstimation] Starting for ${services.length} services (model: ${model.name})`);

  for (const svc of services) {
    try {
      let dau: number;
      let isEstimatedDau: boolean;
      let totalCalls: number;

      if (svc.type === 'STANDARD') {
        const stats = stdMap.get(svc.id);
        dau = stats?.dau || 0;
        totalCalls = stats?.calls || 0;
        isEstimatedDau = false;
      } else {
        totalCalls = bgMap.get(svc.id) || 0;
        dau = callsPerPersonPerDay > 0 ? Math.round(totalCalls / callsPerPersonPerDay) : 0;
        isEstimatedDau = true;
      }

      // 사용량 0이면 스킵
      if (totalCalls === 0) continue;

      const prompt = buildPrompt(svc, dau, isEstimatedDau, totalCalls);
      const raw = await callSystemLlm(model, prompt);
      const result = parseEstimation(raw);

      if (!result) {
        console.error(`[AiEstimation] Failed to parse LLM response for "${svc.name}":`, raw.substring(0, 200));
        errors++;
        continue;
      }

      await prisma.aiEstimation.upsert({
        where: { serviceId_date: { serviceId: svc.id, date: yesterdayDate } },
        update: {
          estimatedMM: result.estimatedMM,
          confidence: result.confidence,
          reasoning: result.reasoning,
          dauUsed: dau,
          isEstimatedDau,
          totalCalls,
          modelId: model.id,
        },
        create: {
          serviceId: svc.id,
          date: yesterdayDate,
          estimatedMM: result.estimatedMM,
          confidence: result.confidence,
          reasoning: result.reasoning,
          dauUsed: dau,
          isEstimatedDau,
          totalCalls,
          modelId: model.id,
        },
      });

      processed++;
      console.log(`[AiEstimation] ${svc.name}: ${result.estimatedMM} M/M (${result.confidence})`);

      // Rate limit 방지 딜레이
      await new Promise(r => setTimeout(r, DELAY_BETWEEN_CALLS_MS));
    } catch (err) {
      console.error(`[AiEstimation] Error for "${svc.name}":`, err);
      errors++;
    }
  }

  // 5. 오래된 추정 삭제
  try {
    const cutoff = new Date();
    cutoff.setDate(cutoff.getDate() - RETENTION_DAYS);
    const deleted = await prisma.aiEstimation.deleteMany({ where: { createdAt: { lt: cutoff } } });
    if (deleted.count > 0) console.log(`[AiEstimation] Cleaned up ${deleted.count} old estimations`);
  } catch (err) {
    console.error('[AiEstimation] Cleanup failed:', err);
  }

  console.log(`[AiEstimation] Done: ${processed} processed, ${errors} errors`);
  return { processed, errors };
}

// ── Cron 스케줄러 ──
export function startAiEstimationCron(): void {
  // 1시간마다 체크, 자정(KST 00:00~00:59)이면 실행
  estimationInterval = setInterval(async () => {
    const kstHour = new Date(Date.now() + 9 * 60 * 60 * 1000).getUTCHours();
    if (kstHour !== 0) return; // 자정이 아니면 스킵

    const today = new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString().split('T')[0];
    if (lastRunDate === today) return; // 오늘 이미 실행됨

    lastRunDate = today;
    console.log(`[AiEstimation] Midnight KST — starting daily estimation`);
    await runAiEstimations().catch(err => console.error('[AiEstimation] Cron failed:', err));
  }, ESTIMATION_INTERVAL_MS);

  console.log('[AiEstimation] Cron scheduled (runs daily at midnight KST)');
}

export function stopAiEstimationCron(): void {
  if (estimationInterval) {
    clearInterval(estimationInterval);
    estimationInterval = null;
  }
}
