/**
 * AI Estimation Service
 *
 * 매일 자정(KST) 서비스별 전일 DAU + 설명을 시스템 LLM에 보내
 * M/M 절감 효과를 추정하여 ai_estimations 테이블에 저장.
 */

import { prisma } from '../index.js';
import { logInternalLlmUsage } from './internalUsageLogger.js';

const ESTIMATION_INTERVAL_MS = 60 * 60 * 1000; // 1시간마다 체크
const LLM_TIMEOUT_MS = 60_000; // 60초
const DELAY_BETWEEN_CALLS_MS = 2_000; // 서비스 간 2초 딜레이 (rate limit 방지)
const RETENTION_DAYS = 90;

let estimationInterval: ReturnType<typeof setInterval> | null = null;
let lastRunDate = ''; // YYYY-MM-DD 형식 — 하루에 한 번만 실행

// ── System Prompt ──
const SYSTEM_PROMPT = `You are an expert business analyst specializing in IT workforce productivity measurement.
Your task is to estimate the current M/M (Man-Month) cost savings generated by an AI-powered service based on its usage data and description.

Key definitions:
- 1 M/M = 1 person working full-time for 1 month (≈20 business days, 160 hours)
- 1 M/D = 1 person working 1 full day = 0.05 M/M

You must respond ONLY with valid JSON, no other text.`;

// ── LLM 호출 ──
async function callSystemLlm(
  model: { id?: string; name: string; endpointUrl: string; apiKey: string | null; extraHeaders: unknown; extraBody: unknown },
  prompt: string,
  logPath: string = '/internal/ai-estimation',
): Promise<string> {
  let url = model.endpointUrl.trim();
  if (!url.endsWith('/chat/completions')) {
    if (url.endsWith('/')) url = url.slice(0, -1);
    url = `${url}/chat/completions`;
  }

  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (model.apiKey) headers['Authorization'] = `Bearer ${model.apiKey}`;
  if (model.extraHeaders && typeof model.extraHeaders === 'object') {
    for (const [k, v] of Object.entries(model.extraHeaders as Record<string, string>)) {
      const lower = k.toLowerCase();
      if (lower !== 'content-type' && lower !== 'authorization') headers[k] = v;
    }
  }

  const body = {
    ...(model.extraBody && typeof model.extraBody === 'object' ? model.extraBody : {}),
    model: model.name,
    messages: [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: prompt },
    ],
    max_tokens: 1024,
    temperature: 0.3,
    stream: false,
  };

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), LLM_TIMEOUT_MS);
  const startMs = Date.now();

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers,
      body: JSON.stringify(body),
      signal: controller.signal,
    });
    clearTimeout(timeoutId);
    const latencyMs = Date.now() - startMs;

    if (!response.ok) {
      const errText = await response.text().catch(() => '');
      if (model.id) {
        logInternalLlmUsage({
          modelId: model.id, modelName: model.name,
          inputTokens: 0, outputTokens: 0, latencyMs,
          path: logPath, statusCode: response.status,
          errorMessage: errText.substring(0, 300),
        });
      }
      throw new Error(`LLM ${response.status}: ${errText.substring(0, 300)}`);
    }

    const data = await response.json() as {
      choices?: Array<{ message?: { content?: string } }>;
      usage?: { prompt_tokens?: number; completion_tokens?: number };
    };

    // 사용량 로깅
    if (model.id) {
      logInternalLlmUsage({
        modelId: model.id, modelName: model.name,
        inputTokens: data.usage?.prompt_tokens || 0,
        outputTokens: data.usage?.completion_tokens || 0,
        latencyMs, path: logPath,
      });
    }

    return data.choices?.[0]?.message?.content || '';
  } catch (err) {
    clearTimeout(timeoutId);
    throw err;
  }
}

// ── 프롬프트 빌더 (서비스 전체) ──
function buildPrompt(service: {
  displayName: string;
  type: string;
  description: string | null;
  targetMM: number | null;
  savedMM: number | null;
  createdAt: Date;
}, avgDau: number, isEstimatedDau: boolean, avgCalls: number, numDays: number): string {
  const callsPerUser = avgDau > 0 ? Math.round(avgCalls / avgDau * 10) / 10 : 0;

  return [
    `You are estimating M/M (Man-Month) savings for an AI service.`,
    ``,
    `Your reasoning MUST follow this structure:`,
    `1. Based on the service description and usage data (LLM call count, token usage), estimate the per-DAU M/M effect — how much time does 1 daily active user save per month by using this service?`,
    `2. Then multiply: with MAU of X and avg DAU of Y, the total estimated M/M savings is calculated.`,
    ``,
    `Key definitions:`,
    `- 1 M/M = 1 person × 1 month full-time (≈20 business days, 160 hours)`,
    `- 1 M/D = 0.05 M/M`,
    ``,
    `Service: ${service.displayName}`,
    `Type: ${service.type} (${service.type === 'STANDARD' ? 'interactive user-facing' : 'automated batch processing'})`,
    `Description: ${service.description || 'No description'}`,
    ...(service.type === 'BACKGROUND' ? [`Type: automated batch processing`] : []),
    ``,
    `Usage data (avg of last ${numDays} business days):`,
    `- Avg daily DAU: ${avgDau}${isEstimatedDau ? ' (estimated)' : ''}`,
    `- Avg daily LLM calls: ${avgCalls} (${callsPerUser} calls/user/day)`,
    `- Owner's target M/M: ${service.targetMM ?? 'not set'}`,
    `- Manually recorded Saved M/M: ${service.savedMM ?? 'not set'}`,
    ``,
    `Respond ONLY with valid JSON:`,
    `{"estimatedMM": <number 1 decimal>, "confidence": "HIGH"|"MEDIUM"|"LOW", "reasoning": "<Korean. 서비스 설명과 사용량을 보니 DAU 1인당 ~의 M/M 효과가 예상되고, MAU X명·평균 DAU Y명이므로 현재 ~의 M/M 효과를 보고있는 것으로 추정된다 형식으로 작성>"}`,
  ].join('\n');
}

// ── JSON 파싱 (안전) ──
function parseEstimation(raw: string): { estimatedMM: number; confidence: string; reasoning: string } | null {
  try {
    // JSON 블록 추출 (```json ... ``` 감싸기 대응)
    const jsonMatch = raw.match(/\{[\s\S]*"estimatedMM"[\s\S]*\}/);
    if (!jsonMatch) return null;
    const parsed = JSON.parse(jsonMatch[0]);
    const mm = parseFloat(parsed.estimatedMM);
    if (isNaN(mm)) return null;
    return {
      estimatedMM: Math.round(mm * 10) / 10,
      confidence: ['HIGH', 'MEDIUM', 'LOW'].includes(parsed.confidence) ? parsed.confidence : 'MEDIUM',
      reasoning: String(parsed.reasoning || '').substring(0, 2000),
    };
  } catch {
    return null;
  }
}

// ── 최근 5영업일 평균 DAU + 호출 수 조회 (주말/휴일 제외, 오늘 제외) ──
async function getRecentBusinessDayStats(todayKST: Date) {
  // 오늘 제외, 과거 30일 범위에서 영업일 5일을 찾음
  const rangeEnd = new Date(todayKST);
  rangeEnd.setDate(rangeEnd.getDate() - 1); // 어제부터
  rangeEnd.setHours(23, 59, 59, 999);
  const rangeStart = new Date(todayKST);
  rangeStart.setDate(rangeStart.getDate() - 31); // 넉넉히 31일 전
  rangeStart.setHours(0, 0, 0, 0);

  // STANDARD: 서비스별 일별 DAU + 호출 수 (영업일만)
  const standardDaily = await prisma.$queryRaw<
    Array<{ service_id: string; d: Date; dau: bigint; calls: bigint }>
  >`
    SELECT ul.service_id::text as service_id,
           DATE(ul.timestamp) as d,
           COUNT(DISTINCT ul.user_id) as dau,
           COALESCE(SUM(ul.request_count), 0) as calls
    FROM usage_logs ul
    INNER JOIN users u ON ul.user_id = u.id
    WHERE ul.timestamp >= ${rangeStart} AND ul.timestamp <= ${rangeEnd}
      AND u.loginid != 'anonymous' AND u.is_test_account = false
      AND ul.service_id IS NOT NULL
      AND EXTRACT(DOW FROM ul.timestamp) NOT IN (0, 6)
      AND NOT EXISTS (SELECT 1 FROM holidays h WHERE h.date = DATE(ul.timestamp))
    GROUP BY ul.service_id, DATE(ul.timestamp)
    ORDER BY DATE(ul.timestamp) DESC
  `;

  // BACKGROUND: 일별 호출 수 (영업일만)
  const bgDaily = await prisma.$queryRaw<
    Array<{ service_id: string; d: Date; calls: bigint }>
  >`
    SELECT service_id::text as service_id,
           DATE(timestamp) as d,
           COALESCE(SUM(request_count), 0) as calls
    FROM usage_logs
    WHERE timestamp >= ${rangeStart} AND timestamp <= ${rangeEnd}
      AND service_id IS NOT NULL
      AND EXTRACT(DOW FROM timestamp) NOT IN (0, 6)
      AND NOT EXISTS (SELECT 1 FROM holidays h WHERE h.date = DATE(timestamp))
    GROUP BY service_id, DATE(timestamp)
    ORDER BY DATE(timestamp) DESC
  `;

  // 영업일 목록 (최근 5일만)
  const bizDaysSet = new Set<string>();
  for (const r of [...standardDaily, ...bgDaily]) {
    bizDaysSet.add(new Date(r.d).toISOString().split('T')[0]);
  }
  const bizDays = [...bizDaysSet].sort().reverse().slice(0, 5);
  const bizDaySet = new Set(bizDays);
  const numDays = bizDays.length;

  if (numDays === 0) {
    return { stdMap: new Map(), bgMap: new Map(), callsPerPersonPerDay: 0, numDays: 0 };
  }

  // STANDARD: 5영업일 평균 DAU + 호출 수
  const stdAgg = new Map<string, { totalDau: number; totalCalls: number }>();
  for (const r of standardDaily) {
    const day = new Date(r.d).toISOString().split('T')[0];
    if (!bizDaySet.has(day)) continue;
    const cur = stdAgg.get(r.service_id) || { totalDau: 0, totalCalls: 0 };
    cur.totalDau += Number(r.dau);
    cur.totalCalls += Number(r.calls);
    stdAgg.set(r.service_id, cur);
  }
  const stdMap = new Map<string, { dau: number; calls: number }>();
  for (const [id, v] of stdAgg) {
    stdMap.set(id, { dau: Math.round(v.totalDau / numDays), calls: Math.round(v.totalCalls / numDays) });
  }

  // BACKGROUND: 5영업일 평균 호출 수
  const bgAgg = new Map<string, number>();
  for (const r of bgDaily) {
    const day = new Date(r.d).toISOString().split('T')[0];
    if (!bizDaySet.has(day)) continue;
    bgAgg.set(r.service_id, (bgAgg.get(r.service_id) || 0) + Number(r.calls));
  }
  const bgMap = new Map<string, number>();
  for (const [id, total] of bgAgg) {
    bgMap.set(id, Math.round(total / numDays));
  }

  // STANDARD 기준 1인당 하루 평균 호출 수 (BACKGROUND DAU 추정 베이스라인)
  let totalStdCalls = 0;
  let totalStdDau = 0;
  for (const v of stdAgg.values()) {
    totalStdCalls += v.totalCalls;
    totalStdDau += v.totalDau;
  }
  const avgStdCalls = totalStdCalls / numDays;
  const avgStdDau = totalStdDau / numDays;
  const callsPerPersonPerDay = avgStdDau > 0 ? avgStdCalls / avgStdDau : 0;

  return { stdMap, bgMap, callsPerPersonPerDay, numDays };
}

// ── 메인 실행 ──
export async function runAiEstimations(): Promise<{ processed: number; errors: number }> {
  // 1. 시스템 LLM 설정 확인
  const setting = await prisma.systemSetting.findUnique({ where: { key: 'SYSTEM_LLM_MODEL_ID' } });
  if (!setting?.value) {
    console.log('[AiEstimation] System LLM not configured — skipping');
    return { processed: 0, errors: 0 };
  }

  const model = await prisma.model.findUnique({
    where: { id: setting.value },
    select: { id: true, name: true, endpointUrl: true, apiKey: true, extraHeaders: true, extraBody: true, enabled: true, type: true },
  });
  if (!model || !model.enabled || model.type !== 'CHAT') {
    console.log('[AiEstimation] System LLM not found, disabled, or not CHAT type — skipping');
    return { processed: 0, errors: 0 };
  }

  // 2. 오늘 날짜 (KST)
  const now = new Date();
  const kstNow = new Date(now.getTime() + 9 * 60 * 60 * 1000);
  const todayKST = new Date(Date.UTC(kstNow.getUTCFullYear(), kstNow.getUTCMonth(), kstNow.getUTCDate()));

  // 3. 배포된 서비스 목록
  const services = await prisma.service.findMany({
    where: { status: 'DEPLOYED' },
    select: {
      id: true, name: true, displayName: true, description: true,
      type: true, apiOnly: true, targetMM: true, savedMM: true, createdAt: true,
    },
  });

  if (services.length === 0) {
    console.log('[AiEstimation] No deployed services — skipping');
    return { processed: 0, errors: 0 };
  }

  // 4. 최근 5영업일 평균 사용 통계
  const { stdMap, bgMap, callsPerPersonPerDay, numDays } = await getRecentBusinessDayStats(todayKST);

  if (numDays === 0) {
    console.log('[AiEstimation] No recent business days with data — skipping');
    return { processed: 0, errors: 0 };
  }

  let processed = 0;
  let errors = 0;

  console.log(`[AiEstimation] Starting for ${services.length} services (model: ${model.name})`);

  for (const svc of services) {
    try {
      let avgDau: number;
      let isEstimatedDau: boolean;
      let avgCalls: number;

      if (svc.type === 'STANDARD') {
        const stats = stdMap.get(svc.id);
        avgDau = stats?.dau || 0;
        avgCalls = stats?.calls || 0;
        isEstimatedDau = false;
      } else {
        avgCalls = bgMap.get(svc.id) || 0;
        avgDau = callsPerPersonPerDay > 0 ? Math.round(avgCalls / callsPerPersonPerDay) : 0;
        isEstimatedDau = true;
      }

      // 사용량 0이면 스킵
      if (avgCalls === 0) continue;

      const prompt = buildPrompt(svc, avgDau, isEstimatedDau, avgCalls, numDays);
      const raw = await callSystemLlm(model, prompt);
      const result = parseEstimation(raw);

      if (!result) {
        console.error(`[AiEstimation] Failed to parse LLM response for "${svc.name}":`, raw.substring(0, 200));
        errors++;
        continue;
      }

      await prisma.aiEstimation.upsert({
        where: { serviceId_date: { serviceId: svc.id, date: todayKST } },
        update: {
          estimatedMM: result.estimatedMM,
          confidence: result.confidence,
          reasoning: result.reasoning,
          dauUsed: avgDau,
          isEstimatedDau,
          totalCalls: avgCalls,
          modelId: model.id,
        },
        create: {
          serviceId: svc.id,
          date: todayKST,
          estimatedMM: result.estimatedMM,
          confidence: result.confidence,
          reasoning: result.reasoning,
          dauUsed: avgDau,
          isEstimatedDau,
          totalCalls: avgCalls,
          modelId: model.id,
        },
      });

      processed++;
      console.log(`[AiEstimation] ${svc.name}: ${result.estimatedMM} M/M (${result.confidence})`);

      // Rate limit 방지 딜레이
      await new Promise(r => setTimeout(r, DELAY_BETWEEN_CALLS_MS));
    } catch (err) {
      console.error(`[AiEstimation] Error for "${svc.name}":`, err);
      errors++;
    }
  }

  // 5. 오래된 추정 삭제
  try {
    const cutoff = new Date();
    cutoff.setDate(cutoff.getDate() - RETENTION_DAYS);
    const deleted = await prisma.aiEstimation.deleteMany({ where: { createdAt: { lt: cutoff } } });
    if (deleted.count > 0) console.log(`[AiEstimation] Cleaned up ${deleted.count} old estimations`);
  } catch (err) {
    console.error('[AiEstimation] Cleanup failed:', err);
  }

  console.log(`[AiEstimation] Done: ${processed} processed, ${errors} errors`);
  return { processed, errors };
}

// ── 부서별 프롬프트 빌더 ──
function buildDeptPrompt(service: {
  name: string;
  displayName: string;
  type: string;
  description: string | null;
  createdAt: Date;
}, deptname: string, deptDau: number, deptCalls: number, lastMonthMau: number, currentMonthMau: number, bizDaysElapsed: number, bizDaysTotal: number, savedMM: number | null, deptLlmCallCount: number, deptTotalTokens: number, numBizDays: number): string {
  const callsPerUser = deptDau > 0 ? Math.round(deptCalls / deptDau * 10) / 10 : 0;
  const tokensPerCall = deptLlmCallCount > 0 ? Math.round(deptTotalTokens / deptLlmCallCount) : 0;
  const avgDailyCalls = numBizDays > 0 ? Math.round(deptLlmCallCount / numBizDays) : 0;
  const avgDailyTokens = numBizDays > 0 ? Math.round(deptTotalTokens / numBizDays) : 0;

  return [
    `You are estimating the M/M (Man-Month) savings that department "${deptname}" gets from using an AI service.`,
    ``,
    `Your reasoning MUST follow this structure:`,
    `1. Look at the service description, LLM call count (${deptLlmCallCount.toLocaleString()} total over ${numBizDays} business days), and token usage (${(deptTotalTokens / 1000000).toFixed(2)}M tokens) to understand the complexity and nature of work being automated.`,
    `2. Estimate per-DAU M/M effect: how much time does 1 daily active user save per month by using this service? Consider that each user makes ~${callsPerUser} calls/day with ~${tokensPerCall} tokens/call.`,
    `3. Then calculate total: with MAU ${lastMonthMau}명 and avg DAU ${deptDau}명, the total M/M savings is estimated.`,
    ``,
    `Key definitions:`,
    `- 1 M/M = 1 person × 1 month full-time (≈20 business days, 160 hours)`,
    `- 1 M/D = 0.05 M/M`,
    ``,
    `Service: ${service.displayName} (${service.name})`,
    `Type: ${service.type} (${service.type === 'STANDARD' ? 'interactive user-facing' : 'automated batch processing'})`,
    `Description: ${service.description || 'No description'}`,
    ``,
    `Department "${deptname}" usage data (last ${numBizDays} business days):`,
    `- Avg daily active users (DAU): ${deptDau}`,
    `- Avg daily LLM calls: ${deptCalls} (${callsPerUser} calls/user/day)`,
    `- Total LLM call count (${numBizDays}d): ${deptLlmCallCount.toLocaleString()} (avg ${avgDailyCalls.toLocaleString()}/day)`,
    `- Total token usage (${numBizDays}d): ${deptTotalTokens.toLocaleString()} tokens (${(deptTotalTokens / 1000000).toFixed(2)}M, avg ${avgDailyTokens.toLocaleString()}/day, ~${tokensPerCall} tokens/call)`,
    `- Last month MAU: ${lastMonthMau}`,
    `- Current month MAU: ${currentMonthMau} (${bizDaysElapsed}/${bizDaysTotal} business days elapsed)`,
    `- Manually recorded Saved M/M: ${savedMM ?? 'not set'}`,
    ``,
    `Respond ONLY with valid JSON:`,
    `{"estimatedMM": <number 1 decimal>, "confidence": "HIGH"|"MEDIUM"|"LOW", "reasoning": "<Korean. 최근 ${numBizDays}영업일 기준 LLM 호출량(${deptLlmCallCount.toLocaleString()}회), 토큰 사용량(${(deptTotalTokens / 1000000).toFixed(2)}M)을 보니 DAU 1인당 ~의 M/M 효과가 예상되고, MAU ${lastMonthMau}명·평균 DAU ${deptDau}명이므로 현재 ~의 M/M 효과를 보고있는 것으로 추정된다 형식으로 작성>"}`,
  ].join('\n');
}

// ── KST 영업일 계산 helpers ──
function getKstNow(): Date {
  const now = new Date();
  return new Date(now.getTime() + 9 * 60 * 60 * 1000);
}

function getMonthBoundariesKST(kstNow: Date, monthOffset: number): { start: Date; end: Date } {
  const year = kstNow.getUTCFullYear();
  const month = kstNow.getUTCMonth() + monthOffset;
  // start: 1일 00:00 KST → UTC
  const start = new Date(Date.UTC(year, month, 1, -9, 0, 0));
  // end: 다음달 1일 00:00 KST → UTC
  const end = new Date(Date.UTC(year, month + 1, 1, -9, 0, 0));
  return { start, end };
}

function countWeekdaysInRange(start: Date, end: Date): number {
  let count = 0;
  const cursor = new Date(start);
  while (cursor < end) {
    const dow = cursor.getUTCDay();
    if (dow !== 0 && dow !== 6) count++;
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }
  return count;
}

// ── 부서별 AI 추정 ──
export async function runDeptAiEstimations(): Promise<{ processed: number; errors: number }> {
  // 1. 시스템 LLM 설정 확인
  const setting = await prisma.systemSetting.findUnique({ where: { key: 'SYSTEM_LLM_MODEL_ID' } });
  if (!setting?.value) {
    console.log('[DeptAiEstimation] System LLM not configured — skipping');
    return { processed: 0, errors: 0 };
  }

  const model = await prisma.model.findUnique({
    where: { id: setting.value },
    select: { id: true, name: true, endpointUrl: true, apiKey: true, extraHeaders: true, extraBody: true, enabled: true, type: true },
  });
  if (!model || !model.enabled || model.type !== 'CHAT') {
    console.log('[DeptAiEstimation] System LLM not found, disabled, or not CHAT type — skipping');
    return { processed: 0, errors: 0 };
  }

  // 2. 배포된 서비스 목록
  const services = await prisma.service.findMany({
    where: { status: 'DEPLOYED' },
    select: {
      id: true, name: true, displayName: true, description: true,
      type: true, createdAt: true,
    },
  });

  if (services.length === 0) {
    console.log('[DeptAiEstimation] No deployed services — skipping');
    return { processed: 0, errors: 0 };
  }

  // 3. KST 시간 계산
  const kstNow = getKstNow();
  const todayKST = new Date(Date.UTC(kstNow.getUTCFullYear(), kstNow.getUTCMonth(), kstNow.getUTCDate()));

  // 최근 5영업일 범위
  const rangeEnd = new Date(todayKST);
  rangeEnd.setDate(rangeEnd.getDate() - 1);
  rangeEnd.setHours(23, 59, 59, 999);
  const rangeStart = new Date(todayKST);
  rangeStart.setDate(rangeStart.getDate() - 31);
  rangeStart.setHours(0, 0, 0, 0);

  // 지난달/이번달 경계
  const lastMonth = getMonthBoundariesKST(kstNow, -1);
  const currentMonth = getMonthBoundariesKST(kstNow, 0);
  const currentMonthBizTotal = countWeekdaysInRange(
    new Date(Date.UTC(kstNow.getUTCFullYear(), kstNow.getUTCMonth(), 1)),
    new Date(Date.UTC(kstNow.getUTCFullYear(), kstNow.getUTCMonth() + 1, 1)),
  );
  // 이번달 경과 영업일 (오늘까지)
  const currentMonthBizElapsed = countWeekdaysInRange(
    new Date(Date.UTC(kstNow.getUTCFullYear(), kstNow.getUTCMonth(), 1)),
    new Date(Date.UTC(kstNow.getUTCFullYear(), kstNow.getUTCMonth(), kstNow.getUTCDate() + 1)),
  );

  // 4. 서비스별 부서 사용 현황 조회 (최근 5영업일 기준 DAU/calls/tokens)
  const deptDailyStats = await prisma.$queryRaw<
    Array<{ service_id: string; deptname: string; d: Date; dau: bigint; calls: bigint; total_tokens: bigint }>
  >`
    SELECT ul.service_id::text as service_id,
           u.deptname,
           DATE(ul.timestamp) as d,
           COUNT(DISTINCT ul.user_id) as dau,
           COALESCE(SUM(ul.request_count), 0) as calls,
           COALESCE(SUM(ul."totalTokens"), 0) as total_tokens
    FROM usage_logs ul
    INNER JOIN users u ON ul.user_id = u.id
    WHERE ul.timestamp >= ${rangeStart} AND ul.timestamp <= ${rangeEnd}
      AND u.loginid != 'anonymous' AND u.is_test_account = false
      AND ul.service_id IS NOT NULL
      AND u.deptname IS NOT NULL AND u.deptname != ''
      AND EXTRACT(DOW FROM ul.timestamp) NOT IN (0, 6)
      AND NOT EXISTS (SELECT 1 FROM holidays h WHERE h.date = DATE(ul.timestamp))
    GROUP BY ul.service_id, u.deptname, DATE(ul.timestamp)
    ORDER BY DATE(ul.timestamp) DESC
  `;

  // 영업일 목록 (최근 5일만)
  const bizDaysSet = new Set<string>();
  for (const r of deptDailyStats) {
    bizDaysSet.add(new Date(r.d).toISOString().split('T')[0]);
  }
  const bizDays = [...bizDaysSet].sort().reverse().slice(0, 5);
  const bizDaySet = new Set(bizDays);
  const numBizDays = bizDays.length;

  if (numBizDays === 0) {
    console.log('[DeptAiEstimation] No recent business days with data — skipping');
    return { processed: 0, errors: 0 };
  }

  // 서비스+부서별 평균 DAU/calls/tokens 집계
  const deptAgg = new Map<string, Map<string, { totalDau: number; totalCalls: number; totalTokens: number }>>();
  for (const r of deptDailyStats) {
    const day = new Date(r.d).toISOString().split('T')[0];
    if (!bizDaySet.has(day)) continue;
    if (!deptAgg.has(r.service_id)) deptAgg.set(r.service_id, new Map());
    const svcMap = deptAgg.get(r.service_id)!;
    const cur = svcMap.get(r.deptname) || { totalDau: 0, totalCalls: 0, totalTokens: 0 };
    cur.totalDau += Number(r.dau);
    cur.totalCalls += Number(r.calls);
    cur.totalTokens += Number(r.total_tokens);
    svcMap.set(r.deptname, cur);
  }

  // 5. 지난달 MAU (부서별)
  const lastMonthMauRows = await prisma.$queryRaw<
    Array<{ service_id: string; deptname: string; mau: bigint }>
  >`
    SELECT ul.service_id::text as service_id,
           u.deptname,
           COUNT(DISTINCT ul.user_id) as mau
    FROM usage_logs ul
    INNER JOIN users u ON ul.user_id = u.id
    WHERE ul.timestamp >= ${lastMonth.start} AND ul.timestamp < ${lastMonth.end}
      AND u.loginid != 'anonymous' AND u.is_test_account = false
      AND ul.service_id IS NOT NULL
      AND u.deptname IS NOT NULL AND u.deptname != ''
      AND EXTRACT(DOW FROM ul.timestamp) NOT IN (0, 6)
      AND NOT EXISTS (SELECT 1 FROM holidays h WHERE h.date = DATE(ul.timestamp))
    GROUP BY ul.service_id, u.deptname
  `;
  const lastMonthMauMap = new Map<string, Map<string, number>>();
  for (const r of lastMonthMauRows) {
    if (!lastMonthMauMap.has(r.service_id)) lastMonthMauMap.set(r.service_id, new Map());
    lastMonthMauMap.get(r.service_id)!.set(r.deptname, Number(r.mau));
  }

  // 6. 이번달 MAU (부서별)
  const currentMonthMauRows = await prisma.$queryRaw<
    Array<{ service_id: string; deptname: string; mau: bigint }>
  >`
    SELECT ul.service_id::text as service_id,
           u.deptname,
           COUNT(DISTINCT ul.user_id) as mau
    FROM usage_logs ul
    INNER JOIN users u ON ul.user_id = u.id
    WHERE ul.timestamp >= ${currentMonth.start} AND ul.timestamp < ${currentMonth.end}
      AND u.loginid != 'anonymous' AND u.is_test_account = false
      AND ul.service_id IS NOT NULL
      AND u.deptname IS NOT NULL AND u.deptname != ''
      AND EXTRACT(DOW FROM ul.timestamp) NOT IN (0, 6)
      AND NOT EXISTS (SELECT 1 FROM holidays h WHERE h.date = DATE(ul.timestamp))
    GROUP BY ul.service_id, u.deptname
  `;
  const currentMonthMauMap = new Map<string, Map<string, number>>();
  for (const r of currentMonthMauRows) {
    if (!currentMonthMauMap.has(r.service_id)) currentMonthMauMap.set(r.service_id, new Map());
    currentMonthMauMap.get(r.service_id)!.set(r.deptname, Number(r.mau));
  }

  // 7. 기존 DeptServiceSavedMM (manual savedMM 조회)
  const existingSavedMMs = await prisma.deptServiceSavedMM.findMany({
    select: { serviceId: true, deptname: true, savedMM: true },
  });
  const savedMMMap = new Map<string, number | null>();
  for (const r of existingSavedMMs) {
    savedMMMap.set(`${r.serviceId}::${r.deptname}`, r.savedMM);
  }

  let processed = 0;
  let errors = 0;

  console.log(`[DeptAiEstimation] Starting for ${services.length} services (model: ${model.name})`);

  for (const svc of services) {
    try {
      const svcDeptMap = deptAgg.get(svc.id);
      if (!svcDeptMap || svcDeptMap.size === 0) continue;

      for (const [deptname, agg] of svcDeptMap) {
        try {
          const avgDau = Math.round(agg.totalDau / numBizDays);
          const avgCalls = Math.round(agg.totalCalls / numBizDays);

          // 0 사용량 스킵
          if (avgCalls === 0) continue;

          const lmMau = lastMonthMauMap.get(svc.id)?.get(deptname) ?? 0;
          const cmMau = currentMonthMauMap.get(svc.id)?.get(deptname) ?? 0;
          const manualSavedMM = savedMMMap.get(`${svc.id}::${deptname}`) ?? null;
          // 최근 5영업일 총 call count + token usage (deptAgg에서 직접 계산)
          const deptLlmCallCount = agg.totalCalls;
          const deptTotalTokens = agg.totalTokens;

          const prompt = buildDeptPrompt(
            svc, deptname, avgDau, avgCalls,
            lmMau, cmMau,
            currentMonthBizElapsed, currentMonthBizTotal,
            manualSavedMM, deptLlmCallCount, deptTotalTokens,
            numBizDays,
          );

          const raw = await callSystemLlm(model, prompt, '/internal/dept-ai-estimation');
          const result = parseEstimation(raw);

          if (!result) {
            console.error(`[DeptAiEstimation] Failed to parse for "${svc.name}" / "${deptname}":`, raw.substring(0, 200));
            errors++;
            continue;
          }

          // Upsert: AI fields only (preserve manual savedMM)
          await prisma.deptServiceSavedMM.upsert({
            where: { serviceId_deptname: { serviceId: svc.id, deptname } },
            update: {
              aiEstimatedMM: result.estimatedMM,
              aiConfidence: result.confidence,
              aiReasoning: result.reasoning,
            },
            create: {
              serviceId: svc.id,
              deptname,
              aiEstimatedMM: result.estimatedMM,
              aiConfidence: result.confidence,
              aiReasoning: result.reasoning,
            },
          });

          processed++;
          console.log(`[DeptAiEstimation] ${svc.name} / ${deptname}: ${result.estimatedMM} M/M (${result.confidence})`);

          // Rate limit 방지 딜레이
          await new Promise(r => setTimeout(r, DELAY_BETWEEN_CALLS_MS));
        } catch (err) {
          console.error(`[DeptAiEstimation] Error for "${svc.name}" / "${deptname}":`, err);
          errors++;
        }
      }

      // 서비스별 savedMM 재계산: SUM of all dept manual savedMMs
      try {
        const deptSavedRows = await prisma.deptServiceSavedMM.findMany({
          where: { serviceId: svc.id },
          select: { savedMM: true },
        });
        const totalSavedMM = deptSavedRows.reduce((sum, r) => sum + (r.savedMM ?? 0), 0);
        await prisma.service.update({
          where: { id: svc.id },
          data: { savedMM: Math.round(totalSavedMM * 10) / 10 },
        });
      } catch (err) {
        console.error(`[DeptAiEstimation] Failed to recalc savedMM for "${svc.name}":`, err);
      }
    } catch (err) {
      console.error(`[DeptAiEstimation] Error for service "${svc.name}":`, err);
      errors++;
    }
  }

  console.log(`[DeptAiEstimation] Done: ${processed} processed, ${errors} errors`);
  return { processed, errors };
}

// ── Cron 스케줄러 ──
export function startAiEstimationCron(): void {
  // 1시간마다 체크, 자정(KST 00:00~00:59)이면 실행
  estimationInterval = setInterval(async () => {
    const kstHour = new Date(Date.now() + 9 * 60 * 60 * 1000).getUTCHours();
    if (kstHour !== 0) return; // 자정이 아니면 스킵

    const today = new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString().split('T')[0];
    if (lastRunDate === today) return; // 오늘 이미 실행됨

    lastRunDate = today;
    console.log(`[AiEstimation] Midnight KST — starting daily estimation`);
    await runAiEstimations().catch(err => console.error('[AiEstimation] Cron failed:', err));
    // 부서별 AI 추정 실행 (per-service 추정 완료 후)
    await runDeptAiEstimations().catch(err => console.error('[DeptAiEstimation] Cron failed:', err));
  }, ESTIMATION_INTERVAL_MS);

  console.log('[AiEstimation] Cron scheduled (runs daily at midnight KST)');
}

export function stopAiEstimationCron(): void {
  if (estimationInterval) {
    clearInterval(estimationInterval);
    estimationInterval = null;
  }
}
