/**
 * AI Estimation Service
 *
 * 매일 자정(KST) 서비스별 전일 DAU + 설명을 시스템 LLM에 보내
 * M/M 절감 효과를 추정하여 ai_estimations 테이블에 저장.
 */

import { prisma } from '../index.js';

const ESTIMATION_INTERVAL_MS = 60 * 60 * 1000; // 1시간마다 체크
const LLM_TIMEOUT_MS = 60_000; // 60초
const DELAY_BETWEEN_CALLS_MS = 2_000; // 서비스 간 2초 딜레이 (rate limit 방지)
const RETENTION_DAYS = 90;

let estimationInterval: ReturnType<typeof setInterval> | null = null;
let lastRunDate = ''; // YYYY-MM-DD 형식 — 하루에 한 번만 실행

// ── System Prompt ──
const SYSTEM_PROMPT = `You are an expert business analyst specializing in IT workforce productivity measurement.
Your task is to estimate the current M/M (Man-Month) cost savings generated by an AI-powered service based on its usage data and description.

Key definitions:
- 1 M/M = 1 person working full-time for 1 month (≈20 business days, 160 hours)
- 1 M/D = 1 person working 1 full day = 0.05 M/M

You must respond ONLY with valid JSON, no other text.`;

// ── LLM 호출 ──
async function callSystemLlm(
  model: { name: string; endpointUrl: string; apiKey: string | null; extraHeaders: unknown; extraBody: unknown },
  prompt: string,
): Promise<string> {
  let url = model.endpointUrl.trim();
  if (!url.endsWith('/chat/completions')) {
    if (url.endsWith('/')) url = url.slice(0, -1);
    // /v1으로 끝나면 /chat/completions만 추가, 아니면 그대로 /chat/completions 추가
    // (대부분의 엔드포인트 URL은 이미 /v1까지 포함하거나, /chat/completions를 포함)
    url = `${url}/chat/completions`;
  }

  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (model.apiKey) headers['Authorization'] = `Bearer ${model.apiKey}`;
  if (model.extraHeaders && typeof model.extraHeaders === 'object') {
    for (const [k, v] of Object.entries(model.extraHeaders as Record<string, string>)) {
      const lower = k.toLowerCase();
      if (lower !== 'content-type' && lower !== 'authorization') headers[k] = v;
    }
  }

  const body = {
    ...(model.extraBody && typeof model.extraBody === 'object' ? model.extraBody : {}),
    model: model.name,
    messages: [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: prompt },
    ],
    max_tokens: 1024,
    temperature: 0.3,
    stream: false,
  };

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), LLM_TIMEOUT_MS);

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers,
      body: JSON.stringify(body),
      signal: controller.signal,
    });
    clearTimeout(timeoutId);

    if (!response.ok) {
      const errText = await response.text().catch(() => '');
      throw new Error(`LLM ${response.status}: ${errText.substring(0, 300)}`);
    }

    const data = await response.json() as { choices?: Array<{ message?: { content?: string } }> };
    return data.choices?.[0]?.message?.content || '';
  } catch (err) {
    clearTimeout(timeoutId);
    throw err;
  }
}

// ── 프롬프트 빌더 ──
function buildPrompt(service: {
  displayName: string;
  type: string;
  description: string | null;
  standardMD: number | null;
  targetMM: number | null;
  savedMM: number | null;
  createdAt: Date;
}, avgDau: number, isEstimatedDau: boolean, avgCalls: number, numDays: number): string {
  const lines = [
    `Estimate the M/M savings for this AI service:`,
    ``,
    `Service: ${service.displayName}`,
    `Type: ${service.type} (${service.type === 'STANDARD' ? 'interactive user-facing' : 'automated batch processing'})`,
    `Description: ${service.description || 'No description'}`,
  ];

  if (service.type === 'BACKGROUND' && service.standardMD) {
    lines.push(`Standard workload per task: ${service.standardMD} M/D`);
  }

  lines.push(
    ``,
    `Recent usage (avg of last ${numDays} business days, excluding weekends/holidays):`,
    `- Avg daily DAU: ${avgDau}${isEstimatedDau ? ' (estimated from API call volume)' : ''}`,
    `- Avg daily API calls: ${avgCalls}`,
    ``,
    `Context:`,
    `- Running since: ${service.createdAt.toISOString().split('T')[0]}`,
    `- Owner's target M/M: ${service.targetMM ?? 'not set'}`,
    `- Manually recorded Saved M/M: ${service.savedMM ?? 'not set'}`,
  );

  if (service.type === 'BACKGROUND' && service.standardMD) {
    lines.push(`- For BACKGROUND: Saved M/M ≈ daily_tasks × ${service.standardMD} M/D ÷ 20`);
  }

  lines.push(
    ``,
    `Respond in JSON:`,
    `{"estimatedMM": <number 1 decimal>, "confidence": "HIGH"|"MEDIUM"|"LOW", "reasoning": "<2-3 sentences in Korean>"}`,
  );

  return lines.join('\n');
}

// ── JSON 파싱 (안전) ──
function parseEstimation(raw: string): { estimatedMM: number; confidence: string; reasoning: string } | null {
  try {
    // JSON 블록 추출 (```json ... ``` 감싸기 대응)
    const jsonMatch = raw.match(/\{[\s\S]*"estimatedMM"[\s\S]*\}/);
    if (!jsonMatch) return null;
    const parsed = JSON.parse(jsonMatch[0]);
    const mm = parseFloat(parsed.estimatedMM);
    if (isNaN(mm)) return null;
    return {
      estimatedMM: Math.round(mm * 10) / 10,
      confidence: ['HIGH', 'MEDIUM', 'LOW'].includes(parsed.confidence) ? parsed.confidence : 'MEDIUM',
      reasoning: String(parsed.reasoning || '').substring(0, 2000),
    };
  } catch {
    return null;
  }
}

// ── 최근 5영업일 평균 DAU + 호출 수 조회 (주말/휴일 제외, 오늘 제외) ──
async function getRecentBusinessDayStats(todayKST: Date) {
  // 오늘 제외, 과거 30일 범위에서 영업일 5일을 찾음
  const rangeEnd = new Date(todayKST);
  rangeEnd.setDate(rangeEnd.getDate() - 1); // 어제부터
  rangeEnd.setHours(23, 59, 59, 999);
  const rangeStart = new Date(todayKST);
  rangeStart.setDate(rangeStart.getDate() - 31); // 넉넉히 31일 전
  rangeStart.setHours(0, 0, 0, 0);

  // STANDARD: 서비스별 일별 DAU + 호출 수 (영업일만)
  const standardDaily = await prisma.$queryRaw<
    Array<{ service_id: string; d: Date; dau: bigint; calls: bigint }>
  >`
    SELECT ul.service_id::text as service_id,
           DATE(ul.timestamp) as d,
           COUNT(DISTINCT ul.user_id) as dau,
           COUNT(*) as calls
    FROM usage_logs ul
    INNER JOIN users u ON ul.user_id = u.id
    WHERE ul.timestamp >= ${rangeStart} AND ul.timestamp <= ${rangeEnd}
      AND u.loginid != 'anonymous'
      AND ul.service_id IS NOT NULL
      AND EXTRACT(DOW FROM ul.timestamp) NOT IN (0, 6)
      AND NOT EXISTS (SELECT 1 FROM holidays h WHERE h.date = DATE(ul.timestamp))
    GROUP BY ul.service_id, DATE(ul.timestamp)
    ORDER BY DATE(ul.timestamp) DESC
  `;

  // BACKGROUND: 일별 호출 수 (영업일만)
  const bgDaily = await prisma.$queryRaw<
    Array<{ service_id: string; d: Date; calls: bigint }>
  >`
    SELECT service_id::text as service_id,
           DATE(timestamp) as d,
           COUNT(*) as calls
    FROM usage_logs
    WHERE timestamp >= ${rangeStart} AND timestamp <= ${rangeEnd}
      AND service_id IS NOT NULL
      AND EXTRACT(DOW FROM timestamp) NOT IN (0, 6)
      AND NOT EXISTS (SELECT 1 FROM holidays h WHERE h.date = DATE(timestamp))
    GROUP BY service_id, DATE(timestamp)
    ORDER BY DATE(timestamp) DESC
  `;

  // 영업일 목록 (최근 5일만)
  const bizDaysSet = new Set<string>();
  for (const r of [...standardDaily, ...bgDaily]) {
    bizDaysSet.add(new Date(r.d).toISOString().split('T')[0]);
  }
  const bizDays = [...bizDaysSet].sort().reverse().slice(0, 5);
  const bizDaySet = new Set(bizDays);
  const numDays = bizDays.length;

  if (numDays === 0) {
    return { stdMap: new Map(), bgMap: new Map(), callsPerPersonPerDay: 0, numDays: 0 };
  }

  // STANDARD: 5영업일 평균 DAU + 호출 수
  const stdAgg = new Map<string, { totalDau: number; totalCalls: number }>();
  for (const r of standardDaily) {
    const day = new Date(r.d).toISOString().split('T')[0];
    if (!bizDaySet.has(day)) continue;
    const cur = stdAgg.get(r.service_id) || { totalDau: 0, totalCalls: 0 };
    cur.totalDau += Number(r.dau);
    cur.totalCalls += Number(r.calls);
    stdAgg.set(r.service_id, cur);
  }
  const stdMap = new Map<string, { dau: number; calls: number }>();
  for (const [id, v] of stdAgg) {
    stdMap.set(id, { dau: Math.round(v.totalDau / numDays), calls: Math.round(v.totalCalls / numDays) });
  }

  // BACKGROUND: 5영업일 평균 호출 수
  const bgAgg = new Map<string, number>();
  for (const r of bgDaily) {
    const day = new Date(r.d).toISOString().split('T')[0];
    if (!bizDaySet.has(day)) continue;
    bgAgg.set(r.service_id, (bgAgg.get(r.service_id) || 0) + Number(r.calls));
  }
  const bgMap = new Map<string, number>();
  for (const [id, total] of bgAgg) {
    bgMap.set(id, Math.round(total / numDays));
  }

  // API Only STANDARD 서비스의 daily_usage_stats 데이터도 baseline에 포함
  const apiOnlyStdServices = await prisma.service.findMany({
    where: { apiOnly: true, type: 'STANDARD', status: 'DEPLOYED' },
    select: { id: true },
  });
  const apiOnlyStdIds = apiOnlyStdServices.map(s => s.id);

  let extStdDau = 0;
  let extStdCalls = 0;
  if (apiOnlyStdIds.length > 0) {
    const extDaily = await prisma.$queryRaw<
      Array<{ d: Date; total_dau: bigint; total_calls: bigint }>
    >`
      SELECT date as d,
             COUNT(DISTINCT user_id) as total_dau,
             COALESCE(SUM("requestCount"), 0) as total_calls
      FROM daily_usage_stats
      WHERE date >= ${rangeStart} AND date <= ${rangeEnd}
        AND service_id::text = ANY(${apiOnlyStdIds})
        AND user_id IS NOT NULL
        AND EXTRACT(DOW FROM date) NOT IN (0, 6)
        AND NOT EXISTS (SELECT 1 FROM holidays h WHERE h.date = daily_usage_stats.date)
      GROUP BY date
      ORDER BY date DESC
    `;
    for (const r of extDaily) {
      const day = new Date(r.d).toISOString().split('T')[0];
      if (!bizDaySet.has(day)) continue;
      extStdDau += Number(r.total_dau);
      extStdCalls += Number(r.total_calls);
    }
  }

  // API Only BACKGROUND 서비스의 daily_usage_stats 호출 데이터도 bgMap에 포함
  const apiOnlyBgServices = await prisma.service.findMany({
    where: { apiOnly: true, type: 'BACKGROUND', status: 'DEPLOYED' },
    select: { id: true },
  });
  const apiOnlyBgIds = apiOnlyBgServices.map(s => s.id);

  if (apiOnlyBgIds.length > 0) {
    const extBgDaily = await prisma.$queryRaw<
      Array<{ service_id: string; total_calls: bigint }>
    >`
      SELECT service_id::text as service_id,
             COALESCE(SUM("requestCount"), 0) as total_calls
      FROM daily_usage_stats
      WHERE date >= ${rangeStart} AND date <= ${rangeEnd}
        AND service_id::text = ANY(${apiOnlyBgIds})
        AND EXTRACT(DOW FROM date) NOT IN (0, 6)
        AND NOT EXISTS (SELECT 1 FROM holidays h WHERE h.date = daily_usage_stats.date)
      GROUP BY service_id
    `;
    for (const r of extBgDaily) {
      const existing = bgMap.get(r.service_id) || 0;
      bgMap.set(r.service_id, existing + Math.round(Number(r.total_calls) / numDays));
    }
  }

  // STANDARD 기준 1인당 하루 평균 호출 수 (BACKGROUND DAU 추정 베이스라인)
  // API Only STANDARD 데이터도 합산
  let totalStdCalls = 0;
  let totalStdDau = 0;
  for (const v of stdAgg.values()) {
    totalStdCalls += v.totalCalls;
    totalStdDau += v.totalDau;
  }
  totalStdCalls += extStdCalls;
  totalStdDau += extStdDau;
  const avgStdCalls = totalStdCalls / numDays;
  const avgStdDau = totalStdDau / numDays;
  const callsPerPersonPerDay = avgStdDau > 0 ? avgStdCalls / avgStdDau : 0;

  return { stdMap, bgMap, callsPerPersonPerDay, numDays };
}

// ── 메인 실행 ──
export async function runAiEstimations(): Promise<{ processed: number; errors: number }> {
  // 1. 시스템 LLM 설정 확인
  const setting = await prisma.systemSetting.findUnique({ where: { key: 'SYSTEM_LLM_MODEL_ID' } });
  if (!setting?.value) {
    console.log('[AiEstimation] System LLM not configured — skipping');
    return { processed: 0, errors: 0 };
  }

  const model = await prisma.model.findUnique({
    where: { id: setting.value },
    select: { id: true, name: true, endpointUrl: true, apiKey: true, extraHeaders: true, extraBody: true, enabled: true, type: true },
  });
  if (!model || !model.enabled || model.type !== 'CHAT') {
    console.log('[AiEstimation] System LLM not found, disabled, or not CHAT type — skipping');
    return { processed: 0, errors: 0 };
  }

  // 2. 오늘 날짜 (KST)
  const now = new Date();
  const kstNow = new Date(now.getTime() + 9 * 60 * 60 * 1000);
  const todayKST = new Date(Date.UTC(kstNow.getUTCFullYear(), kstNow.getUTCMonth(), kstNow.getUTCDate()));

  // 3. 배포된 서비스 목록
  const services = await prisma.service.findMany({
    where: { status: 'DEPLOYED' },
    select: {
      id: true, name: true, displayName: true, description: true,
      type: true, apiOnly: true, standardMD: true, targetMM: true, savedMM: true, createdAt: true,
    },
  });

  if (services.length === 0) {
    console.log('[AiEstimation] No deployed services — skipping');
    return { processed: 0, errors: 0 };
  }

  // 4. 최근 5영업일 평균 사용 통계
  const { stdMap, bgMap, callsPerPersonPerDay, numDays } = await getRecentBusinessDayStats(todayKST);

  if (numDays === 0) {
    console.log('[AiEstimation] No recent business days with data — skipping');
    return { processed: 0, errors: 0 };
  }

  let processed = 0;
  let errors = 0;

  console.log(`[AiEstimation] Starting for ${services.length} services (model: ${model.name})`);

  for (const svc of services) {
    try {
      let avgDau: number;
      let isEstimatedDau: boolean;
      let avgCalls: number;

      if (svc.type === 'STANDARD') {
        const stats = stdMap.get(svc.id);
        avgDau = stats?.dau || 0;
        avgCalls = stats?.calls || 0;
        isEstimatedDau = false;

        // API Only STANDARD: DailyUsageStat에서 영업일 기준 데이터 보충
        if (svc.apiOnly) {
          const extRangeEnd = new Date(todayKST);
          extRangeEnd.setDate(extRangeEnd.getDate() - 1);
          const extRangeStart = new Date(todayKST);
          extRangeStart.setDate(extRangeStart.getDate() - 31);
          const extStats = await prisma.$queryRaw<
            Array<{ avg_dau: number; avg_calls: number }>
          >`
            WITH daily AS (
              SELECT date as d,
                     COUNT(DISTINCT user_id) as dau,
                     COALESCE(SUM("requestCount"), 0) as calls
              FROM daily_usage_stats
              WHERE service_id = ${svc.id}::uuid
                AND date >= ${extRangeStart} AND date <= ${extRangeEnd}
                AND user_id IS NOT NULL
                AND EXTRACT(DOW FROM date) NOT IN (0, 6)
                AND NOT EXISTS (SELECT 1 FROM holidays h WHERE h.date = daily_usage_stats.date)
              GROUP BY date
              ORDER BY date DESC
              LIMIT 5
            )
            SELECT COALESCE(AVG(dau), 0)::float as avg_dau,
                   COALESCE(AVG(calls), 0)::float as avg_calls
            FROM daily
          `;
          avgDau += Math.round(extStats[0]?.avg_dau || 0);
          avgCalls += Math.round(extStats[0]?.avg_calls || 0);
        }
      } else {
        avgCalls = bgMap.get(svc.id) || 0;
        avgDau = callsPerPersonPerDay > 0 ? Math.round(avgCalls / callsPerPersonPerDay) : 0;
        isEstimatedDau = true;
      }

      // 사용량 0이면 스킵
      if (avgCalls === 0) continue;

      const prompt = buildPrompt(svc, avgDau, isEstimatedDau, avgCalls, numDays);
      const raw = await callSystemLlm(model, prompt);
      const result = parseEstimation(raw);

      if (!result) {
        console.error(`[AiEstimation] Failed to parse LLM response for "${svc.name}":`, raw.substring(0, 200));
        errors++;
        continue;
      }

      await prisma.aiEstimation.upsert({
        where: { serviceId_date: { serviceId: svc.id, date: todayKST } },
        update: {
          estimatedMM: result.estimatedMM,
          confidence: result.confidence,
          reasoning: result.reasoning,
          dauUsed: avgDau,
          isEstimatedDau,
          totalCalls: avgCalls,
          modelId: model.id,
        },
        create: {
          serviceId: svc.id,
          date: todayKST,
          estimatedMM: result.estimatedMM,
          confidence: result.confidence,
          reasoning: result.reasoning,
          dauUsed: avgDau,
          isEstimatedDau,
          totalCalls: avgCalls,
          modelId: model.id,
        },
      });

      processed++;
      console.log(`[AiEstimation] ${svc.name}: ${result.estimatedMM} M/M (${result.confidence})`);

      // Rate limit 방지 딜레이
      await new Promise(r => setTimeout(r, DELAY_BETWEEN_CALLS_MS));
    } catch (err) {
      console.error(`[AiEstimation] Error for "${svc.name}":`, err);
      errors++;
    }
  }

  // 5. 오래된 추정 삭제
  try {
    const cutoff = new Date();
    cutoff.setDate(cutoff.getDate() - RETENTION_DAYS);
    const deleted = await prisma.aiEstimation.deleteMany({ where: { createdAt: { lt: cutoff } } });
    if (deleted.count > 0) console.log(`[AiEstimation] Cleaned up ${deleted.count} old estimations`);
  } catch (err) {
    console.error('[AiEstimation] Cleanup failed:', err);
  }

  console.log(`[AiEstimation] Done: ${processed} processed, ${errors} errors`);
  return { processed, errors };
}

// ── Cron 스케줄러 ──
export function startAiEstimationCron(): void {
  // 1시간마다 체크, 자정(KST 00:00~00:59)이면 실행
  estimationInterval = setInterval(async () => {
    const kstHour = new Date(Date.now() + 9 * 60 * 60 * 1000).getUTCHours();
    if (kstHour !== 0) return; // 자정이 아니면 스킵

    const today = new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString().split('T')[0];
    if (lastRunDate === today) return; // 오늘 이미 실행됨

    lastRunDate = today;
    console.log(`[AiEstimation] Midnight KST — starting daily estimation`);
    await runAiEstimations().catch(err => console.error('[AiEstimation] Cron failed:', err));
  }, ESTIMATION_INTERVAL_MS);

  console.log('[AiEstimation] Cron scheduled (runs daily at midnight KST)');
}

export function stopAiEstimationCron(): void {
  if (estimationInterval) {
    clearInterval(estimationInterval);
    estimationInterval = null;
  }
}
