# Dev upstream — dev 서버 전용
upstream api {
    server api-dev:3000;
    keepalive 256;
    keepalive_requests 1000;
    keepalive_timeout 60s;
}

upstream dashboard {
    server dashboard-dev:80;
    keepalive 128;
    keepalive_requests 1000;
    keepalive_timeout 60s;
}
